
package com.exasol.adapter.document.edml;

/**
 * Abstract base for EDML mappings that map to an Exasol {@code VARCHAR} column.
 */

public abstract class AbstractToVarcharColumnMapping extends AbstractToColumnMapping {
    private final int varcharColumnSize;

    /**
     * Builder class. The content of the builder is generated by lombok. We need this class declared here since the
     * Javadoc generation fails otherwise.
     *
     * @param <C> type used by lombok
     * @param <B> type used by lombok
     */
    public abstract static class AbstractToVarcharColumnMappingBuilder<C extends AbstractToVarcharColumnMapping, B extends AbstractToVarcharColumnMappingBuilder<C, B>>
            extends AbstractToColumnMappingBuilder<C, B> {

        private boolean varcharColumnSize$set;

        private int varcharColumnSize$value;

        @java.lang.Override

        protected abstract B self();

        @java.lang.Override

        public abstract C build();

        /**
         * @return {@code this}.
         */

        public B varcharColumnSize(final int varcharColumnSize) {
            this.varcharColumnSize$value = varcharColumnSize;
            varcharColumnSize$set = true;
            return self();
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "AbstractToVarcharColumnMapping.AbstractToVarcharColumnMappingBuilder(super=" + super.toString()
                    + ", varcharColumnSize$value=" + this.varcharColumnSize$value + ")";
        }
    }

    private static int $default$varcharColumnSize() {
        return 254;
    }

    protected AbstractToVarcharColumnMapping(
            final AbstractToVarcharColumnMapping.AbstractToVarcharColumnMappingBuilder<?, ?> b) {
        super(b);
        if (b.varcharColumnSize$set)
            this.varcharColumnSize = b.varcharColumnSize$value;
        else
            this.varcharColumnSize = AbstractToVarcharColumnMapping.$default$varcharColumnSize();
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof AbstractToVarcharColumnMapping))
            return false;
        final AbstractToVarcharColumnMapping other = (AbstractToVarcharColumnMapping) o;
        if (!other.canEqual((java.lang.Object) this))
            return false;
        if (!super.equals(o))
            return false;
        if (this.getVarcharColumnSize() != other.getVarcharColumnSize())
            return false;
        return true;
    }

    @Override
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AbstractToVarcharColumnMapping;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        result = result * PRIME + this.getVarcharColumnSize();
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "AbstractToVarcharColumnMapping(super=" + super.toString() + ", varcharColumnSize="
                + this.getVarcharColumnSize() + ")";
    }

    public int getVarcharColumnSize() {
        return this.varcharColumnSize;
    }
}
