
package com.exasol.adapter.document.edml;

/**
 * Abstract base for EDML mappings that map to an Exasol {@code VARCHAR} column.
 */

public abstract class AbstractToVarcharColumnMapping extends AbstractToColumnMapping {
    private final int varcharColumnSize;

    /**
     * Builder class. The content of the builder is generated by lombok. We need this class declared here since the
     * Javadoc generation fails otherwise.
     *
     * @param <C> type used by lombok
     * @param <B> type used by lombok
     */
    public abstract static class AbstractToVarcharColumnMappingBuilder<C extends AbstractToVarcharColumnMapping, B extends AbstractToVarcharColumnMappingBuilder<C, B>>
            extends AbstractToColumnMappingBuilder<C, B> {

        private boolean varcharColumnSize$set;

        private int varcharColumnSize$value;

        @Override
        protected abstract B self();

        @Override
        public abstract C build();

        /**
         * @param varcharColumnSize size for {@code VARCHAR} columns
         * @return {@code this}.
         */
        public B varcharColumnSize(final int varcharColumnSize) {
            this.varcharColumnSize$value = varcharColumnSize;
            this.varcharColumnSize$set = true;
            return self();
        }

        @Override
        public String toString() {
            return "AbstractToVarcharColumnMapping.AbstractToVarcharColumnMappingBuilder(super=" + super.toString()
                    + ", varcharColumnSize$value=" + this.varcharColumnSize$value + ")";
        }
    }

    private static int $default$varcharColumnSize() {
        return 254;
    }

    /**
     * Create a new {@link AbstractToVarcharColumnMapping}.
     * 
     * @param builder the builder
     */
    protected AbstractToVarcharColumnMapping(
            final AbstractToVarcharColumnMapping.AbstractToVarcharColumnMappingBuilder<?, ?> builder) {
        super(builder);
        if (builder.varcharColumnSize$set) {
            this.varcharColumnSize = builder.varcharColumnSize$value;
        } else {
            this.varcharColumnSize = AbstractToVarcharColumnMapping.$default$varcharColumnSize();
        }
    }

    @Override
    public boolean equals(final Object o) {
        if (o == this) {
            return true;
        }
        if (!(o instanceof AbstractToVarcharColumnMapping)) {
            return false;
        }
        final AbstractToVarcharColumnMapping other = (AbstractToVarcharColumnMapping) o;
        if (!other.canEqual(this)) {
            return false;
        }
        if (!super.equals(o)) {
            return false;
        }
        if (this.getVarcharColumnSize() != other.getVarcharColumnSize()) {
            return false;
        }
        return true;
    }

    @Override
    protected boolean canEqual(final Object other) {
        return other instanceof AbstractToVarcharColumnMapping;
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        result = (result * PRIME) + this.getVarcharColumnSize();
        return result;
    }

    @Override
    public String toString() {
        return "AbstractToVarcharColumnMapping(super=" + super.toString() + ", varcharColumnSize="
                + this.getVarcharColumnSize() + ")";
    }

    /**
     * Size of the varchar column.
     * 
     * @return size of the varchar column
     */
    public int getVarcharColumnSize() {
        return this.varcharColumnSize;
    }
}
