// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

import lombok.NonNull;

/**
 * Java representation of an EDML definition file.
 */
public class EdmlDefinition {
    @NonNull
    private final String source;
    @NonNull
    private final String destinationTable;
    private final String description;
    private final boolean addSourceReferenceColumn;
    @NonNull
    private final MappingDefinition mapping;
    private final String additionalConfiguration;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$description() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$addSourceReferenceColumn() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$additionalConfiguration() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    EdmlDefinition(@NonNull final String source, @NonNull final String destinationTable, final String description, final boolean addSourceReferenceColumn, @NonNull final MappingDefinition mapping, final String additionalConfiguration) {
        if (source == null) {
            throw new java.lang.NullPointerException("source is marked non-null but is null");
        }
        if (destinationTable == null) {
            throw new java.lang.NullPointerException("destinationTable is marked non-null but is null");
        }
        if (mapping == null) {
            throw new java.lang.NullPointerException("mapping is marked non-null but is null");
        }
        this.source = source;
        this.destinationTable = destinationTable;
        this.description = description;
        this.addSourceReferenceColumn = addSourceReferenceColumn;
        this.mapping = mapping;
        this.additionalConfiguration = additionalConfiguration;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class EdmlDefinitionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String source;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String destinationTable;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean description$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean addSourceReferenceColumn$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean addSourceReferenceColumn$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private MappingDefinition mapping;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean additionalConfiguration$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String additionalConfiguration$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        EdmlDefinitionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder source(@NonNull final String source) {
            if (source == null) {
                throw new java.lang.NullPointerException("source is marked non-null but is null");
            }
            this.source = source;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder destinationTable(@NonNull final String destinationTable) {
            if (destinationTable == null) {
                throw new java.lang.NullPointerException("destinationTable is marked non-null but is null");
            }
            this.destinationTable = destinationTable;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder description(final String description) {
            this.description$value = description;
            description$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder addSourceReferenceColumn(final boolean addSourceReferenceColumn) {
            this.addSourceReferenceColumn$value = addSourceReferenceColumn;
            addSourceReferenceColumn$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder mapping(@NonNull final MappingDefinition mapping) {
            if (mapping == null) {
                throw new java.lang.NullPointerException("mapping is marked non-null but is null");
            }
            this.mapping = mapping;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition.EdmlDefinitionBuilder additionalConfiguration(final String additionalConfiguration) {
            this.additionalConfiguration$value = additionalConfiguration;
            additionalConfiguration$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EdmlDefinition build() {
            String description$value = this.description$value;
            if (!this.description$set) description$value = EdmlDefinition.$default$description();
            boolean addSourceReferenceColumn$value = this.addSourceReferenceColumn$value;
            if (!this.addSourceReferenceColumn$set) addSourceReferenceColumn$value = EdmlDefinition.$default$addSourceReferenceColumn();
            String additionalConfiguration$value = this.additionalConfiguration$value;
            if (!this.additionalConfiguration$set) additionalConfiguration$value = EdmlDefinition.$default$additionalConfiguration();
            return new EdmlDefinition(this.source, this.destinationTable, description$value, addSourceReferenceColumn$value, this.mapping, additionalConfiguration$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "EdmlDefinition.EdmlDefinitionBuilder(source=" + this.source + ", destinationTable=" + this.destinationTable + ", description$value=" + this.description$value + ", addSourceReferenceColumn$value=" + this.addSourceReferenceColumn$value + ", mapping=" + this.mapping + ", additionalConfiguration$value=" + this.additionalConfiguration$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static EdmlDefinition.EdmlDefinitionBuilder builder() {
        return new EdmlDefinition.EdmlDefinitionBuilder();
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSource() {
        return this.source;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDestinationTable() {
        return this.destinationTable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isAddSourceReferenceColumn() {
        return this.addSourceReferenceColumn;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MappingDefinition getMapping() {
        return this.mapping;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdditionalConfiguration() {
        return this.additionalConfiguration;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EdmlDefinition)) return false;
        final EdmlDefinition other = (EdmlDefinition) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAddSourceReferenceColumn() != other.isAddSourceReferenceColumn()) return false;
        final java.lang.Object this$source = this.getSource();
        final java.lang.Object other$source = other.getSource();
        if (this$source == null ? other$source != null : !this$source.equals(other$source)) return false;
        final java.lang.Object this$destinationTable = this.getDestinationTable();
        final java.lang.Object other$destinationTable = other.getDestinationTable();
        if (this$destinationTable == null ? other$destinationTable != null : !this$destinationTable.equals(other$destinationTable)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$mapping = this.getMapping();
        final java.lang.Object other$mapping = other.getMapping();
        if (this$mapping == null ? other$mapping != null : !this$mapping.equals(other$mapping)) return false;
        final java.lang.Object this$additionalConfiguration = this.getAdditionalConfiguration();
        final java.lang.Object other$additionalConfiguration = other.getAdditionalConfiguration();
        if (this$additionalConfiguration == null ? other$additionalConfiguration != null : !this$additionalConfiguration.equals(other$additionalConfiguration)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EdmlDefinition;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAddSourceReferenceColumn() ? 79 : 97);
        final java.lang.Object $source = this.getSource();
        result = result * PRIME + ($source == null ? 43 : $source.hashCode());
        final java.lang.Object $destinationTable = this.getDestinationTable();
        result = result * PRIME + ($destinationTable == null ? 43 : $destinationTable.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $mapping = this.getMapping();
        result = result * PRIME + ($mapping == null ? 43 : $mapping.hashCode());
        final java.lang.Object $additionalConfiguration = this.getAdditionalConfiguration();
        result = result * PRIME + ($additionalConfiguration == null ? 43 : $additionalConfiguration.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "EdmlDefinition(source=" + this.getSource() + ", destinationTable=" + this.getDestinationTable() + ", description=" + this.getDescription() + ", addSourceReferenceColumn=" + this.isAddSourceReferenceColumn() + ", mapping=" + this.getMapping() + ", additionalConfiguration=" + this.getAdditionalConfiguration() + ")";
    }
}
