// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

import lombok.Builder;
// sonar can't deal with Lombok
/**
 * Java representation of the EDML {@code toBoolMapping}.
 */
@SuppressWarnings("java:S1170")
public final class ToBoolMapping extends AbstractToColumnMapping {
    private final ConvertableMappingErrorBehaviour notBooleanBehavior;

    @Override
    public void accept(final MappingDefinitionVisitor visitor) {
        visitor.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static ConvertableMappingErrorBehaviour $default$notBooleanBehavior() {
        return ConvertableMappingErrorBehaviour.ABORT;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static abstract class ToBoolMappingBuilder<C extends ToBoolMapping, B extends ToBoolMapping.ToBoolMappingBuilder<C, B>> extends AbstractToColumnMapping.AbstractToColumnMappingBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean notBooleanBehavior$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ConvertableMappingErrorBehaviour notBooleanBehavior$value;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public B notBooleanBehavior(final ConvertableMappingErrorBehaviour notBooleanBehavior) {
            this.notBooleanBehavior$value = notBooleanBehavior;
            notBooleanBehavior$set = true;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ToBoolMapping.ToBoolMappingBuilder(super=" + super.toString() + ", notBooleanBehavior$value=" + this.notBooleanBehavior$value + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final class ToBoolMappingBuilderImpl extends ToBoolMapping.ToBoolMappingBuilder<ToBoolMapping, ToBoolMapping.ToBoolMappingBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ToBoolMappingBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected ToBoolMapping.ToBoolMappingBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ToBoolMapping build() {
            return new ToBoolMapping(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected ToBoolMapping(final ToBoolMapping.ToBoolMappingBuilder<?, ?> b) {
        super(b);
        if (b.notBooleanBehavior$set) this.notBooleanBehavior = b.notBooleanBehavior$value;
         else this.notBooleanBehavior = ToBoolMapping.$default$notBooleanBehavior();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ToBoolMapping.ToBoolMappingBuilder<?, ?> builder() {
        return new ToBoolMapping.ToBoolMappingBuilderImpl();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ToBoolMapping)) return false;
        final ToBoolMapping other = (ToBoolMapping) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$notBooleanBehavior = this.getNotBooleanBehavior();
        final java.lang.Object other$notBooleanBehavior = other.getNotBooleanBehavior();
        if (this$notBooleanBehavior == null ? other$notBooleanBehavior != null : !this$notBooleanBehavior.equals(other$notBooleanBehavior)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ToBoolMapping;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $notBooleanBehavior = this.getNotBooleanBehavior();
        result = result * PRIME + ($notBooleanBehavior == null ? 43 : $notBooleanBehavior.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ToBoolMapping(super=" + super.toString() + ", notBooleanBehavior=" + this.getNotBooleanBehavior() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ConvertableMappingErrorBehaviour getNotBooleanBehavior() {
        return this.notBooleanBehavior;
    }
}
