// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

// sonar can't deal with Lombok
/**
 * Java representation of the EDML {@code toDateMapping}.
 */
@SuppressWarnings("java:S1170")
public final class ToDateMapping extends AbstractToColumnMapping {
    private final ConvertableMappingErrorBehaviour notDateBehavior;

    @Override
    public void accept(final MappingDefinitionVisitor visitor) {
        visitor.visit(this);
    }

    @java.lang.SuppressWarnings("all")

    private static ConvertableMappingErrorBehaviour $default$notDateBehavior() {
        return ConvertableMappingErrorBehaviour.ABORT;
    }

    @java.lang.SuppressWarnings("all")

    public static abstract class ToDateMappingBuilder<C extends ToDateMapping, B extends ToDateMapping.ToDateMappingBuilder<C, B>>
            extends AbstractToColumnMapping.AbstractToColumnMappingBuilder<C, B> {
        @java.lang.SuppressWarnings("all")

        private boolean notDateBehavior$set;
        @java.lang.SuppressWarnings("all")

        private ConvertableMappingErrorBehaviour notDateBehavior$value;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public B notDateBehavior(final ConvertableMappingErrorBehaviour notDateBehavior) {
            this.notDateBehavior$value = notDateBehavior;
            notDateBehavior$set = true;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public java.lang.String toString() {
            return "ToDateMapping.ToDateMappingBuilder(super=" + super.toString() + ", notDateBehavior$value="
                    + this.notDateBehavior$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")

    private static final class ToDateMappingBuilderImpl
            extends ToDateMapping.ToDateMappingBuilder<ToDateMapping, ToDateMapping.ToDateMappingBuilderImpl> {
        @java.lang.SuppressWarnings("all")

        private ToDateMappingBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        protected ToDateMapping.ToDateMappingBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public ToDateMapping build() {
            return new ToDateMapping(this);
        }
    }

    @java.lang.SuppressWarnings("all")

    protected ToDateMapping(final ToDateMapping.ToDateMappingBuilder<?, ?> b) {
        super(b);
        if (b.notDateBehavior$set)
            this.notDateBehavior = b.notDateBehavior$value;
        else
            this.notDateBehavior = ToDateMapping.$default$notDateBehavior();
    }

    @java.lang.SuppressWarnings("all")

    public static ToDateMapping.ToDateMappingBuilder<?, ?> builder() {
        return new ToDateMapping.ToDateMappingBuilderImpl();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof ToDateMapping))
            return false;
        final ToDateMapping other = (ToDateMapping) o;
        if (!other.canEqual((java.lang.Object) this))
            return false;
        if (!super.equals(o))
            return false;
        final java.lang.Object this$notDateBehavior = this.getNotDateBehavior();
        final java.lang.Object other$notDateBehavior = other.getNotDateBehavior();
        if (this$notDateBehavior == null ? other$notDateBehavior != null
                : !this$notDateBehavior.equals(other$notDateBehavior))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ToDateMapping;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $notDateBehavior = this.getNotDateBehavior();
        result = result * PRIME + ($notDateBehavior == null ? 43 : $notDateBehavior.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public java.lang.String toString() {
        return "ToDateMapping(super=" + super.toString() + ", notDateBehavior=" + this.getNotDateBehavior() + ")";
    }

    @java.lang.SuppressWarnings("all")

    public ConvertableMappingErrorBehaviour getNotDateBehavior() {
        return this.notDateBehavior;
    }
}
