// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

/**
 * Java representation of the EDML {@code toDoubleMapping}.
 */
public final class ToDoubleMapping extends AbstractToNumberMapping {
    @Override
    public void accept(final MappingDefinitionVisitor visitor) {
        visitor.visit(this);
    }

    @java.lang.SuppressWarnings("all")

    public static abstract class ToDoubleMappingBuilder<C extends ToDoubleMapping, B extends ToDoubleMapping.ToDoubleMappingBuilder<C, B>>
            extends AbstractToNumberMapping.AbstractToNumberMappingBuilder<C, B> {
        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public abstract C build();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public java.lang.String toString() {
            return "ToDoubleMapping.ToDoubleMappingBuilder(super=" + super.toString() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")

    private static final class ToDoubleMappingBuilderImpl extends
            ToDoubleMapping.ToDoubleMappingBuilder<ToDoubleMapping, ToDoubleMapping.ToDoubleMappingBuilderImpl> {
        @java.lang.SuppressWarnings("all")

        private ToDoubleMappingBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        protected ToDoubleMapping.ToDoubleMappingBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public ToDoubleMapping build() {
            return new ToDoubleMapping(this);
        }
    }

    @java.lang.SuppressWarnings("all")

    protected ToDoubleMapping(final ToDoubleMapping.ToDoubleMappingBuilder<?, ?> b) {
        super(b);
    }

    @java.lang.SuppressWarnings("all")

    public static ToDoubleMapping.ToDoubleMappingBuilder<?, ?> builder() {
        return new ToDoubleMapping.ToDoubleMappingBuilderImpl();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof ToDoubleMapping))
            return false;
        final ToDoubleMapping other = (ToDoubleMapping) o;
        if (!other.canEqual((java.lang.Object) this))
            return false;
        if (!super.equals(o))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ToDoubleMapping;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public java.lang.String toString() {
        return "ToDoubleMapping(super=" + super.toString() + ")";
    }
}
