// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

// sonar can't deal with Lombok
/**
 * Java representation of the EDML {@code toTableMapping}.
 */
@SuppressWarnings("java:S1170")
public final class ToTableMapping implements MappingDefinition {
    private final String destinationTable;
    private final MappingDefinition mapping;
    private final String description;

    @Override
    public void accept(final MappingDefinitionVisitor visitor) {
        visitor.visit(this);
    }

    @java.lang.SuppressWarnings("all")

    private static String $default$description() {
        return "";
    }

    @java.lang.SuppressWarnings("all")

    ToTableMapping(final String destinationTable, final MappingDefinition mapping, final String description) {
        if (mapping == null) {
            throw new java.lang.NullPointerException("mapping is marked non-null but is null");
        }
        this.destinationTable = destinationTable;
        this.mapping = mapping;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")

    public static class ToTableMappingBuilder {
        @java.lang.SuppressWarnings("all")

        private String destinationTable;
        @java.lang.SuppressWarnings("all")

        private MappingDefinition mapping;
        @java.lang.SuppressWarnings("all")

        private boolean description$set;
        @java.lang.SuppressWarnings("all")

        private String description$value;

        @java.lang.SuppressWarnings("all")

        ToTableMappingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public ToTableMapping.ToTableMappingBuilder destinationTable(final String destinationTable) {
            this.destinationTable = destinationTable;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public ToTableMapping.ToTableMappingBuilder mapping(final MappingDefinition mapping) {
            if (mapping == null) {
                throw new java.lang.NullPointerException("mapping is marked non-null but is null");
            }
            this.mapping = mapping;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public ToTableMapping.ToTableMappingBuilder description(final String description) {
            this.description$value = description;
            description$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")

        public ToTableMapping build() {
            String description$value = this.description$value;
            if (!this.description$set)
                description$value = ToTableMapping.$default$description();
            return new ToTableMapping(this.destinationTable, this.mapping, description$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public java.lang.String toString() {
            return "ToTableMapping.ToTableMappingBuilder(destinationTable=" + this.destinationTable + ", mapping="
                    + this.mapping + ", description$value=" + this.description$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")

    public static ToTableMapping.ToTableMappingBuilder builder() {
        return new ToTableMapping.ToTableMappingBuilder();
    }

    @java.lang.SuppressWarnings("all")

    public String getDestinationTable() {
        return this.destinationTable;
    }

    @java.lang.SuppressWarnings("all")

    public MappingDefinition getMapping() {
        return this.mapping;
    }

    @java.lang.SuppressWarnings("all")

    public String getDescription() {
        return this.description;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof ToTableMapping))
            return false;
        final ToTableMapping other = (ToTableMapping) o;
        final java.lang.Object this$destinationTable = this.getDestinationTable();
        final java.lang.Object other$destinationTable = other.getDestinationTable();
        if (this$destinationTable == null ? other$destinationTable != null
                : !this$destinationTable.equals(other$destinationTable))
            return false;
        final java.lang.Object this$mapping = this.getMapping();
        final java.lang.Object other$mapping = other.getMapping();
        if (this$mapping == null ? other$mapping != null : !this$mapping.equals(other$mapping))
            return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description))
            return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $destinationTable = this.getDestinationTable();
        result = result * PRIME + ($destinationTable == null ? 43 : $destinationTable.hashCode());
        final java.lang.Object $mapping = this.getMapping();
        result = result * PRIME + ($mapping == null ? 43 : $mapping.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public java.lang.String toString() {
        return "ToTableMapping(destinationTable=" + this.getDestinationTable() + ", mapping=" + this.getMapping()
                + ", description=" + this.getDescription() + ")";
    }
}
