// Generated by delombok at Tue Feb 14 11:27:09 CET 2023
package com.exasol.adapter.document.edml;

import lombok.Builder;
// sonar can't deal with Lombok
/**
 * Java representation of the EDML {@code toTimestampMapping}.
 */
@SuppressWarnings("java:S1170")
public final class ToTimestampMapping extends AbstractToColumnMapping {
    private final ConvertableMappingErrorBehaviour notTimestampBehavior;
    /**
     * If set to {@code true} this adapter will use a {@code TIMESTAMP WITH LOCAL TIMEZONE} Exasol column instead of a
     * {@code TIMEZONE} column.
     */
    private final boolean useTimestampWithLocalTimezoneType;

    @Override
    public void accept(final MappingDefinitionVisitor visitor) {
        visitor.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static ConvertableMappingErrorBehaviour $default$notTimestampBehavior() {
        return ConvertableMappingErrorBehaviour.ABORT;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$useTimestampWithLocalTimezoneType() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static abstract class ToTimestampMappingBuilder<C extends ToTimestampMapping, B extends ToTimestampMapping.ToTimestampMappingBuilder<C, B>> extends AbstractToColumnMapping.AbstractToColumnMappingBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean notTimestampBehavior$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ConvertableMappingErrorBehaviour notTimestampBehavior$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean useTimestampWithLocalTimezoneType$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean useTimestampWithLocalTimezoneType$value;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public B notTimestampBehavior(final ConvertableMappingErrorBehaviour notTimestampBehavior) {
            this.notTimestampBehavior$value = notTimestampBehavior;
            notTimestampBehavior$set = true;
            return self();
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public B useTimestampWithLocalTimezoneType(final boolean useTimestampWithLocalTimezoneType) {
            this.useTimestampWithLocalTimezoneType$value = useTimestampWithLocalTimezoneType;
            useTimestampWithLocalTimezoneType$set = true;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ToTimestampMapping.ToTimestampMappingBuilder(super=" + super.toString() + ", notTimestampBehavior$value=" + this.notTimestampBehavior$value + ", useTimestampWithLocalTimezoneType$value=" + this.useTimestampWithLocalTimezoneType$value + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final class ToTimestampMappingBuilderImpl extends ToTimestampMapping.ToTimestampMappingBuilder<ToTimestampMapping, ToTimestampMapping.ToTimestampMappingBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ToTimestampMappingBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected ToTimestampMapping.ToTimestampMappingBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ToTimestampMapping build() {
            return new ToTimestampMapping(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected ToTimestampMapping(final ToTimestampMapping.ToTimestampMappingBuilder<?, ?> b) {
        super(b);
        if (b.notTimestampBehavior$set) this.notTimestampBehavior = b.notTimestampBehavior$value;
         else this.notTimestampBehavior = ToTimestampMapping.$default$notTimestampBehavior();
        if (b.useTimestampWithLocalTimezoneType$set) this.useTimestampWithLocalTimezoneType = b.useTimestampWithLocalTimezoneType$value;
         else this.useTimestampWithLocalTimezoneType = ToTimestampMapping.$default$useTimestampWithLocalTimezoneType();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ToTimestampMapping.ToTimestampMappingBuilder<?, ?> builder() {
        return new ToTimestampMapping.ToTimestampMappingBuilderImpl();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ToTimestampMapping)) return false;
        final ToTimestampMapping other = (ToTimestampMapping) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        if (this.isUseTimestampWithLocalTimezoneType() != other.isUseTimestampWithLocalTimezoneType()) return false;
        final java.lang.Object this$notTimestampBehavior = this.getNotTimestampBehavior();
        final java.lang.Object other$notTimestampBehavior = other.getNotTimestampBehavior();
        if (this$notTimestampBehavior == null ? other$notTimestampBehavior != null : !this$notTimestampBehavior.equals(other$notTimestampBehavior)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ToTimestampMapping;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        result = result * PRIME + (this.isUseTimestampWithLocalTimezoneType() ? 79 : 97);
        final java.lang.Object $notTimestampBehavior = this.getNotTimestampBehavior();
        result = result * PRIME + ($notTimestampBehavior == null ? 43 : $notTimestampBehavior.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ToTimestampMapping(super=" + super.toString() + ", notTimestampBehavior=" + this.getNotTimestampBehavior() + ", useTimestampWithLocalTimezoneType=" + this.isUseTimestampWithLocalTimezoneType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ConvertableMappingErrorBehaviour getNotTimestampBehavior() {
        return this.notTimestampBehavior;
    }

    /**
     * If set to {@code true} this adapter will use a {@code TIMESTAMP WITH LOCAL TIMEZONE} Exasol column instead of a
     * {@code TIMEZONE} column.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isUseTimestampWithLocalTimezoneType() {
        return this.useTimestampWithLocalTimezoneType;
    }
}
